// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#ifndef _PA_CTL_UI_H
#define _PA_CTL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_main.h"
#include "ui_menu.h"
#include "ui_protection.h"
#include "ui_wifi.h"
#include "ui_mainLeft.h"
#include "ui_bands.h"
#include "ui_mainRight.h"
#include "ui_warning.h"
#include "ui_protection2.h"
#include "ui_reservo.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
