// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#ifndef UI_BANDS_H
#define UI_BANDS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_bands
extern void ui_bands_screen_init(void);
extern void ui_bands_screen_destroy(void);
extern void ui_event_bands( lv_event_t * e);
extern lv_obj_t *ui_bands;
extern lv_obj_t *ui_Label28;
extern void ui_event_autoSelectSwitch( lv_event_t * e);
extern lv_obj_t *ui_autoSelectSwitch;
extern void ui_event_Button160m( lv_event_t * e);
extern lv_obj_t *ui_Button160m;
extern void ui_event_Button80m( lv_event_t * e);
extern lv_obj_t *ui_Button80m;
extern void ui_event_Button60m( lv_event_t * e);
extern lv_obj_t *ui_Button60m;
extern void ui_event_Button40m( lv_event_t * e);
extern lv_obj_t *ui_Button40m;
extern lv_obj_t *ui_Label30;
extern lv_obj_t *ui_Label31;
extern lv_obj_t *ui_Label32;
extern lv_obj_t *ui_Label33;
extern void ui_event_Button30m( lv_event_t * e);
extern lv_obj_t *ui_Button30m;
extern void ui_event_Button12m( lv_event_t * e);
extern lv_obj_t *ui_Button12m;
extern void ui_event_Button20m( lv_event_t * e);
extern lv_obj_t *ui_Button20m;
extern void ui_event_Button17m( lv_event_t * e);
extern lv_obj_t *ui_Button17m;
extern void ui_event_Button15m( lv_event_t * e);
extern lv_obj_t *ui_Button15m;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_Label35;
extern lv_obj_t *ui_Label36;
extern lv_obj_t *ui_Label37;
extern lv_obj_t *ui_Label38;
extern void ui_event_Button10m( lv_event_t * e);
extern lv_obj_t *ui_Button10m;
extern void ui_event_Button6m( lv_event_t * e);
extern lv_obj_t *ui_Button6m;
extern lv_obj_t *ui_Label40;
extern lv_obj_t *ui_Label41;
extern void ui_event_Button3( lv_event_t * e);
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

