// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#ifndef UI_MESSAGE_H
#define UI_MESSAGE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_message
extern void ui_message_screen_init(void);
extern void ui_message_screen_destroy(void);
extern lv_obj_t *ui_message;
extern lv_obj_t *ui_Label11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

