// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_main
extern void ui_main_screen_init(void);
extern void ui_main_screen_destroy(void);
extern void ui_event_main( lv_event_t * e);
extern lv_obj_t *ui_main;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_pwrBar;
extern lv_obj_t *ui_pwrTxt;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_swrValue;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_refTxt;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_volTxt;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_current;
extern void ui_event_mainSwitch( lv_event_t * e);
extern lv_obj_t *ui_mainSwitch;
extern void ui_event_menuBtn( lv_event_t * e);
extern lv_obj_t *ui_menuBtn;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label13;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_waterTmp;
extern void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_plateTmp;
extern lv_obj_t *ui_Label58;
extern lv_obj_t *ui_iPWRTxt;
extern lv_obj_t *ui_Label50;
extern lv_obj_t *ui_Label51;
extern lv_obj_t *ui_pumpSTxt;
extern lv_obj_t *ui_fanSTxt;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

