// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#ifndef UI_MAINLEFT_H
#define UI_MAINLEFT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainLeft
extern void ui_mainLeft_screen_init(void);
extern void ui_mainLeft_screen_destroy(void);
extern void ui_event_mainLeft( lv_event_t * e);
extern lv_obj_t *ui_mainLeft;
// Gauge dashboard: four arc meters (colour-zoned by protection limit) plus a
// central column of key electrical readouts. This is a second, graphical view
// of the main-screen telemetry (swipe left from ui_main).
extern lv_obj_t *ui_gPwr;      extern lv_obj_t *ui_gPwrVal;   extern lv_obj_t *ui_spPwr;
extern lv_obj_t *ui_gSwr;      extern lv_obj_t *ui_gSwrVal;
extern lv_obj_t *ui_gWater;    extern lv_obj_t *ui_gWaterVal; extern lv_obj_t *ui_spWater;
extern lv_obj_t *ui_gPlate;    extern lv_obj_t *ui_gPlateVal; extern lv_obj_t *ui_spPlate;
extern lv_obj_t *ui_gCur;
extern lv_obj_t *ui_gVol;
extern lv_obj_t *ui_gCoeff;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

