// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#include "ui.h"

lv_obj_t *ui_mainLeft = NULL;lv_obj_t *ui_Label42 = NULL;lv_obj_t *ui_Label60 = NULL;
// event funtions
void ui_event_mainLeft( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_main_screen_init);
}
}

// build funtions

void ui_mainLeft_screen_init(void)
{
ui_mainLeft = lv_obj_create(NULL);
lv_obj_remove_flag( ui_mainLeft, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label42 = lv_label_create(ui_mainLeft);
lv_obj_set_width( ui_Label42, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label42, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label42, 159 );
lv_obj_set_y( ui_Label42, 111 );
lv_obj_set_align( ui_Label42, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label42,"https://enthru.net");

ui_Label60 = lv_label_create(ui_mainLeft);
lv_obj_set_width( ui_Label60, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label60, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label60, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label60,"Reserved.");

lv_obj_add_event_cb(ui_mainLeft, ui_event_mainLeft, LV_EVENT_ALL, NULL);

}

void ui_mainLeft_screen_destroy(void)
{
   if (ui_mainLeft) lv_obj_del(ui_mainLeft);

// NULL screen variables
ui_mainLeft= NULL;
ui_Label42= NULL;
ui_Label60= NULL;

}
