// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#include "ui.h"

lv_obj_t *ui_mainLeft = NULL;lv_obj_t *ui_Label60 = NULL;lv_obj_t *ui_tempChart = NULL;lv_obj_t *ui_tempChart_Xaxis = NULL;lv_obj_t *ui_tempChart_Yaxis1 = NULL;lv_obj_t *ui_tempChart_Yaxis2 = NULL;lv_obj_t *ui_powerChart = NULL;lv_obj_t *ui_powerChart_Xaxis = NULL;lv_obj_t *ui_powerChart_Yaxis1 = NULL;lv_obj_t *ui_powerChart_Yaxis2 = NULL;lv_obj_t *ui_Label42 = NULL;
// event funtions
void ui_event_mainLeft( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_main_screen_init);
}
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      graphOpened( e );
}
}

// build funtions

void ui_mainLeft_screen_init(void)
{
ui_mainLeft = lv_obj_create(NULL);
lv_obj_remove_flag( ui_mainLeft, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label60 = lv_label_create(ui_mainLeft);
lv_obj_set_width( ui_Label60, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label60, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label60, -193 );
lv_obj_set_y( ui_Label60, -120 );
lv_obj_set_align( ui_Label60, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label60,"Plate temp:");

ui_tempChart = lv_chart_create(ui_mainLeft);
lv_obj_set_width( ui_tempChart, 394);
lv_obj_set_height( ui_tempChart, 85);
lv_obj_set_x( ui_tempChart, 0 );
lv_obj_set_y( ui_tempChart, -57 );
lv_obj_set_align( ui_tempChart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_tempChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_tempChart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_tempChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_tempChart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_tempChart, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_tempChart, 100);

ui_tempChart_Xaxis = lv_scale_create( ui_tempChart );
lv_scale_set_mode( ui_tempChart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_tempChart_Xaxis, lv_pct(100), 50 );
lv_obj_set_align( ui_tempChart_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_tempChart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_tempChart,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_tempChart,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_tempChart_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_tempChart_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_tempChart_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_tempChart_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_tempChart_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_tempChart_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_tempChart_Xaxis, (5>0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_tempChart_Xaxis, 2 >= 1 ? 2 : 1 );
ui_tempChart_Yaxis1 = lv_scale_create( ui_tempChart );
lv_scale_set_mode( ui_tempChart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_tempChart_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_tempChart_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_tempChart_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_tempChart,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_tempChart,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_tempChart_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_tempChart_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_tempChart_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_tempChart_Yaxis1, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_tempChart_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_tempChart_Yaxis1, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_tempChart_Yaxis1, 2 >= 1 ? 2 : 1 );
ui_tempChart_Yaxis2 = lv_scale_create( ui_tempChart );
lv_scale_set_mode( ui_tempChart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_size( ui_tempChart_Yaxis2, 25, lv_pct(100) );
lv_obj_set_align( ui_tempChart_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_tempChart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_tempChart,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_tempChart,LV_PART_MAIN) + 1 );
lv_obj_set_style_line_width( ui_tempChart_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_tempChart_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_tempChart_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_tempChart_Yaxis2, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_tempChart_Yaxis2, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_tempChart_Yaxis2, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_tempChart_Yaxis2, 2 >= 1 ? 2 : 1 );
lv_chart_series_t* ui_tempChart_series_1 = lv_chart_add_series(ui_tempChart, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_tempChart_series_1_array[] = { 0 };
lv_chart_set_ext_y_array(ui_tempChart, ui_tempChart_series_1, ui_tempChart_series_1_array);

//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_tempChart, LV_MAX3(50, 50, 25), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_tempChart, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_powerChart = lv_chart_create(ui_mainLeft);
lv_obj_set_width( ui_powerChart, 389);
lv_obj_set_height( ui_powerChart, 77);
lv_obj_set_x( ui_powerChart, -2 );
lv_obj_set_y( ui_powerChart, 70 );
lv_obj_set_align( ui_powerChart, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_powerChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_remove_flag( ui_powerChart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_add_flag( ui_powerChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE );    //make scales visible - Should it be forced to True? 
//lv_obj_remove_flag( ui_powerChart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
lv_chart_set_type( ui_powerChart, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_powerChart, 100);

ui_powerChart_Xaxis = lv_scale_create( ui_powerChart );
lv_scale_set_mode( ui_powerChart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM );
lv_obj_set_size( ui_powerChart_Xaxis, lv_pct(100), 50 );
lv_obj_set_align( ui_powerChart_Xaxis, LV_ALIGN_BOTTOM_MID );
lv_obj_set_y( ui_powerChart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_powerChart,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_powerChart,LV_PART_MAIN) );
lv_obj_set_style_line_width( ui_powerChart_Xaxis, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_powerChart_Xaxis, 1, LV_PART_ITEMS ); //LVGL-9.1 ticks are thicker by default
lv_obj_set_style_line_width( ui_powerChart_Xaxis, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_powerChart_Xaxis, 5, LV_PART_ITEMS );    //minor tick length
lv_obj_set_style_length( ui_powerChart_Xaxis, 10, LV_PART_INDICATOR );    //major tick length
lv_scale_set_range( ui_powerChart_Xaxis, 0, 5 > 0 ? 5 - 1 : 0 );
lv_scale_set_total_tick_count( ui_powerChart_Xaxis, (5>0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_powerChart_Xaxis, 2 >= 1 ? 2 : 1 );
ui_powerChart_Yaxis1 = lv_scale_create( ui_powerChart );
lv_scale_set_mode( ui_powerChart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT );
lv_obj_set_size( ui_powerChart_Yaxis1, 50, lv_pct(100) );
lv_obj_set_align( ui_powerChart_Yaxis1, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_powerChart_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_powerChart,LV_PART_MAIN) - lv_obj_get_style_border_width(ui_powerChart,LV_PART_MAIN) + 2 );
lv_obj_set_style_line_width( ui_powerChart_Yaxis1, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_powerChart_Yaxis1, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_powerChart_Yaxis1, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_powerChart_Yaxis1, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_powerChart_Yaxis1, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_powerChart_Yaxis1, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_powerChart_Yaxis1, 2 >= 1 ? 2 : 1 );
ui_powerChart_Yaxis2 = lv_scale_create( ui_powerChart );
lv_scale_set_mode( ui_powerChart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT );
lv_obj_set_size( ui_powerChart_Yaxis2, 25, lv_pct(100) );
lv_obj_set_align( ui_powerChart_Yaxis2, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_powerChart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_powerChart,LV_PART_MAIN) + lv_obj_get_style_border_width(ui_powerChart,LV_PART_MAIN) + 1 );
lv_obj_set_style_line_width( ui_powerChart_Yaxis2, 0, LV_PART_MAIN );
lv_obj_set_style_line_width( ui_powerChart_Yaxis2, 1, LV_PART_ITEMS );
lv_obj_set_style_line_width( ui_powerChart_Yaxis2, 1, LV_PART_INDICATOR );
lv_obj_set_style_length( ui_powerChart_Yaxis2, 5, LV_PART_ITEMS ); //minor tick length
lv_obj_set_style_length( ui_powerChart_Yaxis2, 10, LV_PART_INDICATOR ); //major tick length
lv_scale_set_total_tick_count( ui_powerChart_Yaxis2, (5 > 0 ? 5-1 : 0) * 2 + 1 );
lv_scale_set_major_tick_every( ui_powerChart_Yaxis2, 2 >= 1 ? 2 : 1 );
lv_chart_series_t* ui_powerChart_series_1 = lv_chart_add_series(ui_powerChart, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_powerChart_series_1_array[] = { 0 };
lv_chart_set_ext_y_array(ui_powerChart, ui_powerChart_series_1, ui_powerChart_series_1_array);

//This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
lv_obj_set_style_outline_pad( ui_powerChart, LV_MAX3(50, 50, 25), LV_PART_MAIN | LV_STATE_DEFAULT ); //workaround for ineffective 'overflow visible' flag
lv_obj_set_style_outline_width( ui_powerChart, -1, LV_PART_MAIN | LV_STATE_DEFAULT );
ui_Label42 = lv_label_create(ui_mainLeft);
lv_obj_set_width( ui_Label42, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label42, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label42, -209 );
lv_obj_set_y( ui_Label42, 19 );
lv_obj_set_align( ui_Label42, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label42,"Power:");

lv_obj_add_event_cb(ui_mainLeft, ui_event_mainLeft, LV_EVENT_ALL, NULL);

}

void ui_mainLeft_screen_destroy(void)
{
   if (ui_mainLeft) lv_obj_del(ui_mainLeft);

// NULL screen variables
ui_mainLeft= NULL;
ui_Label60= NULL;
ui_tempChart= NULL;
ui_powerChart= NULL;
ui_Label42= NULL;

}
