// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#ifndef UI_MAINRIGHT_H
#define UI_MAINRIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainRight
extern void ui_mainRight_screen_init(void);
extern void ui_mainRight_screen_destroy(void);
extern void ui_event_mainRight( lv_event_t * e);
extern lv_obj_t *ui_mainRight;
extern lv_obj_t *ui_Label43;
extern lv_obj_t *ui_Label44;
extern lv_obj_t *ui_Label45;
extern lv_obj_t *ui_Label46;
extern lv_obj_t *ui_Label47;
extern lv_obj_t *ui_Label48;
extern lv_obj_t *ui_Label49;
extern lv_obj_t *ui_ipADDR;
extern lv_obj_t *ui_SSID;
extern lv_obj_t *ui_uptime;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

