// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#ifndef UI_MAINLEFT_H
#define UI_MAINLEFT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_mainLeft
extern void ui_mainLeft_screen_init(void);
extern void ui_mainLeft_screen_destroy(void);
extern void ui_event_mainLeft( lv_event_t * e);
extern lv_obj_t *ui_mainLeft;
extern lv_obj_t *ui_Chart1;
extern lv_obj_t *ui_Chart1_Xaxis;
extern lv_obj_t *ui_Chart1_Yaxis1;
extern lv_obj_t *ui_Chart1_Yaxis2;
extern lv_obj_t *ui_Label42;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

