// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#include "ui.h"

lv_obj_t *ui_main = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_pwrBar = NULL;lv_obj_t *ui_pwrTxt = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_swrValue = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_refTxt = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_volTxt = NULL;lv_obj_t *ui_Label10 = NULL;lv_obj_t *ui_current = NULL;lv_obj_t *ui_mainSwitch = NULL;lv_obj_t *ui_menuBtn = NULL;lv_obj_t *ui_Label12 = NULL;lv_obj_t *ui_Label13 = NULL;lv_obj_t *ui_Label14 = NULL;lv_obj_t *ui_waterTmp = NULL;lv_obj_t *ui_Button1 = NULL;lv_obj_t *ui_Button2 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_plateTmp = NULL;lv_obj_t *ui_Label58 = NULL;lv_obj_t *ui_iPWRTxt = NULL;
// event funtions
void ui_event_main( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_mainLeft, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_mainLeft_screen_init);
}
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_mainRight, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_mainRight_screen_init);
}
}

void ui_event_mainSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      enableAmp( e );
}
}

void ui_event_menuBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_menu, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_menu_screen_init);
}
}

void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_bands, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_bands_screen_init);
}
}

void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      togglePTT( e );
}
}

// build funtions

void ui_main_screen_init(void)
{
ui_main = lv_obj_create(NULL);
lv_obj_remove_flag( ui_main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -192 );
lv_obj_set_y( ui_Label1, -119 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"POWER:");
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pwrBar = lv_bar_create(ui_main);
lv_bar_set_range(ui_pwrBar, 0,1200);
lv_bar_set_value(ui_pwrBar,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_pwrBar, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_pwrBar, 354);
lv_obj_set_height( ui_pwrBar, 30);
lv_obj_set_x( ui_pwrBar, -56 );
lv_obj_set_y( ui_pwrBar, -90 );
lv_obj_set_align( ui_pwrBar, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_pwrBar,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_pwrBar, lv_obj_get_style_pad_right(ui_pwrBar,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_pwrTxt = lv_label_create(ui_main);
lv_obj_set_width( ui_pwrTxt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pwrTxt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_pwrTxt, 178 );
lv_obj_set_y( ui_pwrTxt, -90 );
lv_obj_set_align( ui_pwrTxt, LV_ALIGN_CENTER );
lv_label_set_text(ui_pwrTxt,"1000W");
lv_obj_set_style_text_font(ui_pwrTxt, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, -204 );
lv_obj_set_y( ui_Label4, -52 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"SWR:");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_swrValue = lv_label_create(ui_main);
lv_obj_set_width( ui_swrValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_swrValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_swrValue, -67 );
lv_obj_set_y( ui_swrValue, -52 );
lv_obj_set_align( ui_swrValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_swrValue,"3.0");
lv_obj_set_style_text_font(ui_swrValue, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label6 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 51 );
lv_obj_set_y( ui_Label6, -59 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"REFLECTED:");
lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_refTxt = lv_label_create(ui_main);
lv_obj_set_width( ui_refTxt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_refTxt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_refTxt, 133 );
lv_obj_set_y( ui_refTxt, -59 );
lv_obj_set_align( ui_refTxt, LV_ALIGN_CENTER );
lv_label_set_text(ui_refTxt,"100W");
lv_obj_set_style_text_font(ui_refTxt, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label8 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label8, -180 );
lv_obj_set_y( ui_Label8, -18 );
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"VOLTAGE:");
lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_volTxt = lv_label_create(ui_main);
lv_obj_set_width( ui_volTxt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_volTxt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_volTxt, -62 );
lv_obj_set_y( ui_volTxt, -18 );
lv_obj_set_align( ui_volTxt, LV_ALIGN_CENTER );
lv_label_set_text(ui_volTxt,"50V");
lv_obj_set_style_text_font(ui_volTxt, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label10 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label10, 58 );
lv_obj_set_y( ui_Label10, 0 );
lv_obj_set_align( ui_Label10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label10,"CURRENT:");
lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_current = lv_label_create(ui_main);
lv_obj_set_width( ui_current, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_current, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_current, 163 );
lv_obj_set_y( ui_current, 0 );
lv_obj_set_align( ui_current, LV_ALIGN_CENTER );
lv_label_set_text(ui_current,"70A");
lv_obj_set_style_text_font(ui_current, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mainSwitch = lv_switch_create(ui_main);
lv_obj_set_width( ui_mainSwitch, 107);
lv_obj_set_height( ui_mainSwitch, 43);
lv_obj_set_x( ui_mainSwitch, -176 );
lv_obj_set_y( ui_mainSwitch, 103 );
lv_obj_set_align( ui_mainSwitch, LV_ALIGN_CENTER );

ui_menuBtn = lv_button_create(ui_main);
lv_obj_set_width( ui_menuBtn, 100);
lv_obj_set_height( ui_menuBtn, 49);
lv_obj_set_x( ui_menuBtn, -48 );
lv_obj_set_y( ui_menuBtn, 99 );
lv_obj_set_align( ui_menuBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_menuBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_menuBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_menuBtn, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label12 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label12, -175 );
lv_obj_set_y( ui_Label12, 67 );
lv_obj_set_align( ui_Label12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label12,"ENABLE");
lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label13 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label13, -49 );
lv_obj_set_y( ui_Label13, 101 );
lv_obj_set_align( ui_Label13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label13,"MENU");
lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label14 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label14, -166 );
lv_obj_set_y( ui_Label14, 15 );
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"WATER TMP:");
lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_waterTmp = lv_label_create(ui_main);
lv_obj_set_width( ui_waterTmp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_waterTmp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_waterTmp, -63 );
lv_obj_set_y( ui_waterTmp, 15 );
lv_obj_set_align( ui_waterTmp, LV_ALIGN_CENTER );
lv_label_set_text(ui_waterTmp,"50C");
lv_obj_set_style_text_font(ui_waterTmp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button1 = lv_button_create(ui_main);
lv_obj_set_width( ui_Button1, 100);
lv_obj_set_height( ui_Button1, 50);
lv_obj_set_x( ui_Button1, 65 );
lv_obj_set_y( ui_Button1, 99 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button2 = lv_button_create(ui_main);
lv_obj_set_width( ui_Button2, 100);
lv_obj_set_height( ui_Button2, 50);
lv_obj_set_x( ui_Button2, 180 );
lv_obj_set_y( ui_Button2, 99 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 62 );
lv_obj_set_y( ui_Label2, 100 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"80m");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 178 );
lv_obj_set_y( ui_Label3, 100 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"PTT");
lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label7, 64 );
lv_obj_set_y( ui_Label7, 28 );
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"PLATE TMP:");
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_plateTmp = lv_label_create(ui_main);
lv_obj_set_width( ui_plateTmp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_plateTmp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_plateTmp, 162 );
lv_obj_set_y( ui_plateTmp, 27 );
lv_obj_set_align( ui_plateTmp, LV_ALIGN_CENTER );
lv_label_set_text(ui_plateTmp,"50C");
lv_obj_set_style_text_font(ui_plateTmp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label58 = lv_label_create(ui_main);
lv_obj_set_width( ui_Label58, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label58, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label58, 50 );
lv_obj_set_y( ui_Label58, -32 );
lv_obj_set_align( ui_Label58, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label58,"INPUT PWR:");
lv_obj_set_style_text_font(ui_Label58, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_iPWRTxt = lv_label_create(ui_main);
lv_obj_set_width( ui_iPWRTxt, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_iPWRTxt, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_iPWRTxt, 135 );
lv_obj_set_y( ui_iPWRTxt, -33 );
lv_obj_set_align( ui_iPWRTxt, LV_ALIGN_CENTER );
lv_label_set_text(ui_iPWRTxt,"10W");
lv_obj_set_style_text_font(ui_iPWRTxt, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_mainSwitch, ui_event_mainSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_menuBtn, ui_event_menuBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_main, ui_event_main, LV_EVENT_ALL, NULL);

}

void ui_main_screen_destroy(void)
{
   if (ui_main) lv_obj_del(ui_main);

// NULL screen variables
ui_main= NULL;
ui_Label1= NULL;
ui_pwrBar= NULL;
ui_pwrTxt= NULL;
ui_Label4= NULL;
ui_swrValue= NULL;
ui_Label6= NULL;
ui_refTxt= NULL;
ui_Label8= NULL;
ui_volTxt= NULL;
ui_Label10= NULL;
ui_current= NULL;
ui_mainSwitch= NULL;
ui_menuBtn= NULL;
ui_Label12= NULL;
ui_Label13= NULL;
ui_Label14= NULL;
ui_waterTmp= NULL;
ui_Button1= NULL;
ui_Button2= NULL;
ui_Label2= NULL;
ui_Label3= NULL;
ui_Label7= NULL;
ui_plateTmp= NULL;
ui_Label58= NULL;
ui_iPWRTxt= NULL;

}
