// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#include "ui.h"

lv_obj_t *ui_message = NULL;lv_obj_t *ui_Label11 = NULL;
// event funtions

// build funtions

void ui_message_screen_init(void)
{
ui_message = lv_obj_create(NULL);
lv_obj_remove_flag( ui_message, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label11 = lv_label_create(ui_message);
lv_obj_set_width( ui_Label11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label11,"text");
lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_message_screen_destroy(void)
{
   if (ui_message) lv_obj_del(ui_message);

// NULL screen variables
ui_message= NULL;
ui_Label11= NULL;

}
