// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#ifndef UI_PROTECTION2_H
#define UI_PROTECTION2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_protection2
extern void ui_protection2_screen_init(void);
extern void ui_protection2_screen_destroy(void);
extern void ui_event_protection2( lv_event_t * e);
extern lv_obj_t *ui_protection2;
extern lv_obj_t *ui_Label20;
extern void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label21;
extern void ui_event_Button7( lv_event_t * e);
extern lv_obj_t *ui_Button7;
extern lv_obj_t *ui_Label29;
extern void ui_event_maxPumpSpdTmpSlider( lv_event_t * e);
extern lv_obj_t *ui_maxPumpSpdTmpSlider;
extern lv_obj_t *ui_Label39;
extern void ui_event_minPumpSpdTmpSlider( lv_event_t * e);
extern lv_obj_t *ui_minPumpSpdTmpSlider;
extern lv_obj_t *ui_Label53;
extern void ui_event_maxFanSpdTmpSlider( lv_event_t * e);
extern lv_obj_t *ui_maxFanSpdTmpSlider;
extern lv_obj_t *ui_Label54;
extern void ui_event_minFanSpdTmpSlider( lv_event_t * e);
extern lv_obj_t *ui_minFanSpdTmpSlider;
extern lv_obj_t *ui_Label55;
extern lv_obj_t *ui_defaultBandDropdown;
extern lv_obj_t *ui_maxPumpSpeedTmp;
extern lv_obj_t *ui_maxFanSpeedTmp;
extern lv_obj_t *ui_minPumpSpeedTmp;
extern lv_obj_t *ui_minFanSpeedTmp;
extern lv_obj_t *ui_protectionSwitch;
extern lv_obj_t *ui_Label52;
extern void ui_event_minCoeffSlider( lv_event_t * e);
extern lv_obj_t *ui_minCoeffSlider;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_minCoeff;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

