// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#ifndef UI_RESERVO_H
#define UI_RESERVO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_reservo
extern void ui_reservo_screen_init(void);
extern void ui_reservo_screen_destroy(void);
extern lv_obj_t *ui_reservo;
extern void ui_event_Button13( lv_event_t * e);
extern lv_obj_t *ui_Button13;
extern lv_obj_t *ui_Label111;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

