// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#include "ui.h"

lv_obj_t *ui_wifi = NULL;lv_obj_t *ui_Keyboard1 = NULL;lv_obj_t *ui_Label25 = NULL;lv_obj_t *ui_TextArea1 = NULL;lv_obj_t *ui_Label26 = NULL;lv_obj_t *ui_TextArea3 = NULL;lv_obj_t *ui_Button10 = NULL;lv_obj_t *ui_Label27 = NULL;
// event funtions
void ui_event_TextArea1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_FOCUSED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
}
}

void ui_event_TextArea3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_FOCUSED) {
      _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea3);
}
}

void ui_event_Button10( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_menu, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_menu_screen_init);
}
}

// build funtions

void ui_wifi_screen_init(void)
{
ui_wifi = lv_obj_create(NULL);
lv_obj_remove_flag( ui_wifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Keyboard1 = lv_keyboard_create(ui_wifi);
lv_obj_set_width( ui_Keyboard1, 471);
lv_obj_set_height( ui_Keyboard1, 152);
lv_obj_set_x( ui_Keyboard1, 0 );
lv_obj_set_y( ui_Keyboard1, 54 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );

ui_Label25 = lv_label_create(ui_wifi);
lv_obj_set_width( ui_Label25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label25, -211 );
lv_obj_set_y( ui_Label25, -119 );
lv_obj_set_align( ui_Label25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label25,"SSID:");

ui_TextArea1 = lv_textarea_create(ui_wifi);
lv_obj_set_width( ui_TextArea1, 150);
lv_obj_set_height( ui_TextArea1, 35);
lv_obj_set_x( ui_TextArea1, -154 );
lv_obj_set_y( ui_TextArea1, -83 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea1,"Placeholder...");

ui_Label26 = lv_label_create(ui_wifi);
lv_obj_set_width( ui_Label26, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label26, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label26, -23 );
lv_obj_set_y( ui_Label26, -119 );
lv_obj_set_align( ui_Label26, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label26,"Password:");

ui_TextArea3 = lv_textarea_create(ui_wifi);
lv_obj_set_width( ui_TextArea3, 150);
lv_obj_set_height( ui_TextArea3, 35);
lv_obj_set_x( ui_TextArea3, 15 );
lv_obj_set_y( ui_TextArea3, -83 );
lv_obj_set_align( ui_TextArea3, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea3,"Placeholder...");
lv_textarea_set_password_mode(ui_TextArea3, true);

ui_Button10 = lv_button_create(ui_wifi);
lv_obj_set_width( ui_Button10, 100);
lv_obj_set_height( ui_Button10, 35);
lv_obj_set_x( ui_Button10, 170 );
lv_obj_set_y( ui_Button10, -84 );
lv_obj_set_align( ui_Button10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button10, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label27 = lv_label_create(ui_wifi);
lv_obj_set_width( ui_Label27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label27, 168 );
lv_obj_set_y( ui_Label27, -84 );
lv_obj_set_align( ui_Label27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label27,"SAVE");
lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_TextArea1, ui_event_TextArea1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextArea3, ui_event_TextArea3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button10, ui_event_Button10, LV_EVENT_ALL, NULL);

}

void ui_wifi_screen_destroy(void)
{
   if (ui_wifi) lv_obj_del(ui_wifi);

// NULL screen variables
ui_wifi= NULL;
ui_Keyboard1= NULL;
ui_Label25= NULL;
ui_TextArea1= NULL;
ui_Label26= NULL;
ui_TextArea3= NULL;
ui_Button10= NULL;
ui_Label27= NULL;

}
