// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_main_screen_init();
ui_menu_screen_init();
ui_protection_screen_init();
ui_wifi_screen_init();
ui_mainLeft_screen_init();
ui_bands_screen_init();
ui_mainRight_screen_init();
ui_warning_screen_init();
ui_protection2_screen_init();
ui_reservo_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_main);
}

void ui_destroy( void )
{ui_main_screen_destroy();
ui_menu_screen_destroy();
ui_protection_screen_destroy();
ui_wifi_screen_destroy();
ui_mainLeft_screen_destroy();
ui_bands_screen_destroy();
ui_mainRight_screen_destroy();
ui_warning_screen_destroy();
ui_protection2_screen_destroy();
ui_reservo_screen_destroy();
}
