// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#include "ui.h"

lv_obj_t *ui_bands = NULL;lv_obj_t *ui_Label28 = NULL;lv_obj_t *ui_autoSelectSwitch = NULL;lv_obj_t *ui_Button160m = NULL;lv_obj_t *ui_Button80m = NULL;lv_obj_t *ui_Button60m = NULL;lv_obj_t *ui_Button40m = NULL;lv_obj_t *ui_Label30 = NULL;lv_obj_t *ui_Label31 = NULL;lv_obj_t *ui_Label32 = NULL;lv_obj_t *ui_Label33 = NULL;lv_obj_t *ui_Button30m = NULL;lv_obj_t *ui_Button12m = NULL;lv_obj_t *ui_Button20m = NULL;lv_obj_t *ui_Button17m = NULL;lv_obj_t *ui_Button15m = NULL;lv_obj_t *ui_Label34 = NULL;lv_obj_t *ui_Label35 = NULL;lv_obj_t *ui_Label36 = NULL;lv_obj_t *ui_Label37 = NULL;lv_obj_t *ui_Label38 = NULL;lv_obj_t *ui_Button10m = NULL;lv_obj_t *ui_Button6m = NULL;lv_obj_t *ui_Label40 = NULL;lv_obj_t *ui_Label41 = NULL;lv_obj_t *ui_Button3 = NULL;lv_obj_t *ui_Label5 = NULL;
// event funtions
void ui_event_bands( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      bandOpened( e );
}
}

void ui_event_autoSelectSwitch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      toggleAutoBand( e );
}
}

void ui_event_Button160m( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_main_screen_init);
      set_band( e );
}
}

void ui_event_Button80m( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_main_screen_init);
      set_band( e );
}
}

void ui_event_Button60m( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_main_screen_init);
      set_band( e );
}
}

void ui_event_Button40m( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_main_screen_init);
      set_band( e );
}
}

void ui_event_Button30m( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_main_screen_init);
      set_band( e );
}
}

void ui_event_Button12m( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_main_screen_init);
      set_band( e );
}
}

void ui_event_Button20m( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_main_screen_init);
      set_band( e );
}
}

void ui_event_Button17m( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_main_screen_init);
      set_band( e );
}
}

void ui_event_Button15m( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_main_screen_init);
      set_band( e );
}
}

void ui_event_Button10m( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_main_screen_init);
      set_band( e );
}
}

void ui_event_Button6m( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_main_screen_init);
      set_band( e );
}
}

void ui_event_Button3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_main_screen_init);
}
}

// build funtions

void ui_bands_screen_init(void)
{
ui_bands = lv_obj_create(NULL);
lv_obj_remove_flag( ui_bands, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label28 = lv_label_create(ui_bands);
lv_obj_set_width( ui_Label28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label28, -127 );
lv_obj_set_y( ui_Label28, -114 );
lv_obj_set_align( ui_Label28, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label28,"AUTO SELECT BAND:");
lv_obj_set_style_text_font(ui_Label28, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_autoSelectSwitch = lv_switch_create(ui_bands);
lv_obj_set_width( ui_autoSelectSwitch, 50);
lv_obj_set_height( ui_autoSelectSwitch, 25);
lv_obj_set_x( ui_autoSelectSwitch, 20 );
lv_obj_set_y( ui_autoSelectSwitch, -114 );
lv_obj_set_align( ui_autoSelectSwitch, LV_ALIGN_CENTER );

ui_Button160m = lv_button_create(ui_bands);
lv_obj_set_width( ui_Button160m, 100);
lv_obj_set_height( ui_Button160m, 50);
lv_obj_set_x( ui_Button160m, -183 );
lv_obj_set_y( ui_Button160m, -26 );
lv_obj_set_align( ui_Button160m, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button160m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button160m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button80m = lv_button_create(ui_bands);
lv_obj_set_width( ui_Button80m, 100);
lv_obj_set_height( ui_Button80m, 50);
lv_obj_set_x( ui_Button80m, -60 );
lv_obj_set_y( ui_Button80m, -26 );
lv_obj_set_align( ui_Button80m, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button80m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button80m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button60m = lv_button_create(ui_bands);
lv_obj_set_width( ui_Button60m, 100);
lv_obj_set_height( ui_Button60m, 50);
lv_obj_set_x( ui_Button60m, 63 );
lv_obj_set_y( ui_Button60m, -27 );
lv_obj_set_align( ui_Button60m, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button60m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button60m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button40m = lv_button_create(ui_bands);
lv_obj_set_width( ui_Button40m, 100);
lv_obj_set_height( ui_Button40m, 50);
lv_obj_set_x( ui_Button40m, 183 );
lv_obj_set_y( ui_Button40m, -27 );
lv_obj_set_align( ui_Button40m, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button40m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button40m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label30 = lv_label_create(ui_bands);
lv_obj_set_width( ui_Label30, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label30, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label30, -183 );
lv_obj_set_y( ui_Label30, -25 );
lv_obj_set_align( ui_Label30, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label30,"160m");
lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label31 = lv_label_create(ui_bands);
lv_obj_set_width( ui_Label31, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label31, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label31, -59 );
lv_obj_set_y( ui_Label31, -25 );
lv_obj_set_align( ui_Label31, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label31,"80m");
lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label32 = lv_label_create(ui_bands);
lv_obj_set_width( ui_Label32, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label32, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label32, 62 );
lv_obj_set_y( ui_Label32, -26 );
lv_obj_set_align( ui_Label32, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label32,"60m");
lv_obj_set_style_text_font(ui_Label32, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label33 = lv_label_create(ui_bands);
lv_obj_set_width( ui_Label33, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label33, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label33, 184 );
lv_obj_set_y( ui_Label33, -26 );
lv_obj_set_align( ui_Label33, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label33,"40m");
lv_obj_set_style_text_font(ui_Label33, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button30m = lv_button_create(ui_bands);
lv_obj_set_width( ui_Button30m, 100);
lv_obj_set_height( ui_Button30m, 50);
lv_obj_set_x( ui_Button30m, -183 );
lv_obj_set_y( ui_Button30m, 36 );
lv_obj_set_align( ui_Button30m, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button30m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button30m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button12m = lv_button_create(ui_bands);
lv_obj_set_width( ui_Button12m, 100);
lv_obj_set_height( ui_Button12m, 50);
lv_obj_set_x( ui_Button12m, -183 );
lv_obj_set_y( ui_Button12m, 100 );
lv_obj_set_align( ui_Button12m, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button12m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button12m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button20m = lv_button_create(ui_bands);
lv_obj_set_width( ui_Button20m, 100);
lv_obj_set_height( ui_Button20m, 50);
lv_obj_set_x( ui_Button20m, -60 );
lv_obj_set_y( ui_Button20m, 36 );
lv_obj_set_align( ui_Button20m, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button20m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button20m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button17m = lv_button_create(ui_bands);
lv_obj_set_width( ui_Button17m, 100);
lv_obj_set_height( ui_Button17m, 50);
lv_obj_set_x( ui_Button17m, 63 );
lv_obj_set_y( ui_Button17m, 36 );
lv_obj_set_align( ui_Button17m, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button17m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button17m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button15m = lv_button_create(ui_bands);
lv_obj_set_width( ui_Button15m, 100);
lv_obj_set_height( ui_Button15m, 50);
lv_obj_set_x( ui_Button15m, 182 );
lv_obj_set_y( ui_Button15m, 36 );
lv_obj_set_align( ui_Button15m, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button15m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button15m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label34 = lv_label_create(ui_bands);
lv_obj_set_width( ui_Label34, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label34, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label34, -184 );
lv_obj_set_y( ui_Label34, 35 );
lv_obj_set_align( ui_Label34, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label34,"30m");
lv_obj_set_style_text_font(ui_Label34, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label35 = lv_label_create(ui_bands);
lv_obj_set_width( ui_Label35, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label35, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label35, -59 );
lv_obj_set_y( ui_Label35, 34 );
lv_obj_set_align( ui_Label35, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label35,"20m");
lv_obj_set_style_text_font(ui_Label35, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label36 = lv_label_create(ui_bands);
lv_obj_set_width( ui_Label36, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label36, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label36, 62 );
lv_obj_set_y( ui_Label36, 35 );
lv_obj_set_align( ui_Label36, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label36,"17m");
lv_obj_set_style_text_font(ui_Label36, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label37 = lv_label_create(ui_bands);
lv_obj_set_width( ui_Label37, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label37, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label37, 184 );
lv_obj_set_y( ui_Label37, 35 );
lv_obj_set_align( ui_Label37, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label37,"15m");
lv_obj_set_style_text_font(ui_Label37, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label38 = lv_label_create(ui_bands);
lv_obj_set_width( ui_Label38, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label38, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label38, -185 );
lv_obj_set_y( ui_Label38, 100 );
lv_obj_set_align( ui_Label38, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label38,"12m");
lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button10m = lv_button_create(ui_bands);
lv_obj_set_width( ui_Button10m, 100);
lv_obj_set_height( ui_Button10m, 50);
lv_obj_set_x( ui_Button10m, -61 );
lv_obj_set_y( ui_Button10m, 100 );
lv_obj_set_align( ui_Button10m, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button10m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button10m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button6m = lv_button_create(ui_bands);
lv_obj_set_width( ui_Button6m, 100);
lv_obj_set_height( ui_Button6m, 50);
lv_obj_set_x( ui_Button6m, 63 );
lv_obj_set_y( ui_Button6m, 100 );
lv_obj_set_align( ui_Button6m, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button6m, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button6m, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label40 = lv_label_create(ui_bands);
lv_obj_set_width( ui_Label40, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label40, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label40, -61 );
lv_obj_set_y( ui_Label40, 100 );
lv_obj_set_align( ui_Label40, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label40,"10m");
lv_obj_set_style_text_font(ui_Label40, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label41 = lv_label_create(ui_bands);
lv_obj_set_width( ui_Label41, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label41, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label41, 61 );
lv_obj_set_y( ui_Label41, 100 );
lv_obj_set_align( ui_Label41, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label41,"6m");
lv_obj_set_style_text_font(ui_Label41, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button3 = lv_button_create(ui_bands);
lv_obj_set_width( ui_Button3, 100);
lv_obj_set_height( ui_Button3, 50);
lv_obj_set_x( ui_Button3, 182 );
lv_obj_set_y( ui_Button3, 99 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_bands);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 181 );
lv_obj_set_y( ui_Label5, 101 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"< BACK");
lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_autoSelectSwitch, ui_event_autoSelectSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button160m, ui_event_Button160m, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button80m, ui_event_Button80m, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button60m, ui_event_Button60m, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button40m, ui_event_Button40m, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button30m, ui_event_Button30m, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button12m, ui_event_Button12m, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button20m, ui_event_Button20m, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button17m, ui_event_Button17m, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button15m, ui_event_Button15m, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button10m, ui_event_Button10m, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button6m, ui_event_Button6m, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_bands, ui_event_bands, LV_EVENT_ALL, NULL);

}

void ui_bands_screen_destroy(void)
{
   if (ui_bands) lv_obj_del(ui_bands);

// NULL screen variables
ui_bands= NULL;
ui_Label28= NULL;
ui_autoSelectSwitch= NULL;
ui_Button160m= NULL;
ui_Button80m= NULL;
ui_Button60m= NULL;
ui_Button40m= NULL;
ui_Label30= NULL;
ui_Label31= NULL;
ui_Label32= NULL;
ui_Label33= NULL;
ui_Button30m= NULL;
ui_Button12m= NULL;
ui_Button20m= NULL;
ui_Button17m= NULL;
ui_Button15m= NULL;
ui_Label34= NULL;
ui_Label35= NULL;
ui_Label36= NULL;
ui_Label37= NULL;
ui_Label38= NULL;
ui_Button10m= NULL;
ui_Button6m= NULL;
ui_Label40= NULL;
ui_Label41= NULL;
ui_Button3= NULL;
ui_Label5= NULL;

}
