// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#include "ui.h"

lv_obj_t *ui_calibration = NULL;lv_obj_t *ui_Button13 = NULL;lv_obj_t *ui_Label111 = NULL;
// event funtions
void ui_event_Button13( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_menu, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_menu_screen_init);
}
}

// build funtions

void ui_calibration_screen_init(void)
{
ui_calibration = lv_obj_create(NULL);
lv_obj_remove_flag( ui_calibration, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button13 = lv_button_create(ui_calibration);
lv_obj_set_width( ui_Button13, 100);
lv_obj_set_height( ui_Button13, 50);
lv_obj_set_x( ui_Button13, -175 );
lv_obj_set_y( ui_Button13, -96 );
lv_obj_set_align( ui_Button13, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button13, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label111 = lv_label_create(ui_calibration);
lv_obj_set_width( ui_Label111, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label111, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label111, -179 );
lv_obj_set_y( ui_Label111, -95 );
lv_obj_set_align( ui_Label111, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label111,"< BACK");
lv_obj_set_style_text_font(ui_Label111, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button13, ui_event_Button13, LV_EVENT_ALL, NULL);

}

void ui_calibration_screen_destroy(void)
{
   if (ui_calibration) lv_obj_del(ui_calibration);

// NULL screen variables
ui_calibration= NULL;
ui_Button13= NULL;
ui_Label111= NULL;

}
