// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#ifndef UI_MENU_H
#define UI_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_menu
extern void ui_menu_screen_init(void);
extern void ui_menu_screen_destroy(void);
extern lv_obj_t *ui_menu;
extern void ui_event_menuBckBtn( lv_event_t * e);
extern lv_obj_t *ui_menuBckBtn;
extern lv_obj_t *ui_Label16;
extern void ui_event_Button5( lv_event_t * e);
extern lv_obj_t *ui_Button5;
extern void ui_event_Button6( lv_event_t * e);
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_Label17;
extern lv_obj_t *ui_Label24;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

