// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#include "ui.h"

lv_obj_t *ui_mainRight = NULL;lv_obj_t *ui_Label43 = NULL;lv_obj_t *ui_Label44 = NULL;lv_obj_t *ui_Label45 = NULL;lv_obj_t *ui_Label46 = NULL;lv_obj_t *ui_Label47 = NULL;lv_obj_t *ui_Label48 = NULL;lv_obj_t *ui_Label49 = NULL;lv_obj_t *ui_ipADDR = NULL;lv_obj_t *ui_SSID = NULL;lv_obj_t *ui_uptime = NULL;
// event funtions
void ui_event_mainRight( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_main_screen_init);
}
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      mainRightLoaded( e );
}
}

// build funtions

void ui_mainRight_screen_init(void)
{
ui_mainRight = lv_obj_create(NULL);
lv_obj_remove_flag( ui_mainRight, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label43 = lv_label_create(ui_mainRight);
lv_obj_set_width( ui_Label43, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label43, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label43, -168 );
lv_obj_set_y( ui_Label43, -115 );
lv_obj_set_align( ui_Label43, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label43,"WI-FI SSID:");
lv_obj_set_style_text_font(ui_Label43, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label44 = lv_label_create(ui_mainRight);
lv_obj_set_width( ui_Label44, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label44, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label44, -169 );
lv_obj_set_y( ui_Label44, -90 );
lv_obj_set_align( ui_Label44, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label44,"IP address:");
lv_obj_set_style_text_font(ui_Label44, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label45 = lv_label_create(ui_mainRight);
lv_obj_set_width( ui_Label45, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label45, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label45, -183 );
lv_obj_set_y( ui_Label45, -66 );
lv_obj_set_align( ui_Label45, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label45,"Uptime:");
lv_obj_set_style_text_font(ui_Label45, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label46 = lv_label_create(ui_mainRight);
lv_obj_set_width( ui_Label46, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label46, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label46, -168 );
lv_obj_set_y( ui_Label46, -42 );
lv_obj_set_align( ui_Label46, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label46,"Max. temp:");
lv_obj_set_style_text_font(ui_Label46, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label47 = lv_label_create(ui_mainRight);
lv_obj_set_width( ui_Label47, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label47, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label47, -171 );
lv_obj_set_y( ui_Label47, -16 );
lv_obj_set_align( ui_Label47, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label47,"Max. SWR:");
lv_obj_set_style_text_font(ui_Label47, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label48 = lv_label_create(ui_mainRight);
lv_obj_set_width( ui_Label48, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label48, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label48, -171 );
lv_obj_set_y( ui_Label48, 120 );
lv_obj_set_align( ui_Label48, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label48,"Backend version:");

ui_Label49 = lv_label_create(ui_mainRight);
lv_obj_set_width( ui_Label49, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label49, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label49, 81 );
lv_obj_set_y( ui_Label49, 119 );
lv_obj_set_align( ui_Label49, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label49,"Frontend version:");

ui_ipADDR = lv_label_create(ui_mainRight);
lv_obj_set_width( ui_ipADDR, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ipADDR, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ipADDR, 6 );
lv_obj_set_y( ui_ipADDR, -90 );
lv_obj_set_align( ui_ipADDR, LV_ALIGN_CENTER );
lv_label_set_text(ui_ipADDR,"XXX");
lv_obj_set_style_text_font(ui_ipADDR, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SSID = lv_label_create(ui_mainRight);
lv_obj_set_width( ui_SSID, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SSID, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SSID, 3 );
lv_obj_set_y( ui_SSID, -114 );
lv_obj_set_align( ui_SSID, LV_ALIGN_CENTER );
lv_label_set_text(ui_SSID,"XXX");
lv_obj_set_style_text_font(ui_SSID, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_uptime = lv_label_create(ui_mainRight);
lv_obj_set_width( ui_uptime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_uptime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_uptime, -3 );
lv_obj_set_y( ui_uptime, -62 );
lv_obj_set_align( ui_uptime, LV_ALIGN_CENTER );
lv_label_set_text(ui_uptime,"XXX");
lv_obj_set_style_text_font(ui_uptime, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_mainRight, ui_event_mainRight, LV_EVENT_ALL, NULL);

}

void ui_mainRight_screen_destroy(void)
{
   if (ui_mainRight) lv_obj_del(ui_mainRight);

// NULL screen variables
ui_mainRight= NULL;
ui_Label43= NULL;
ui_Label44= NULL;
ui_Label45= NULL;
ui_Label46= NULL;
ui_Label47= NULL;
ui_Label48= NULL;
ui_Label49= NULL;
ui_ipADDR= NULL;
ui_SSID= NULL;
ui_uptime= NULL;

}
