// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#include "ui.h"

lv_obj_t *ui_protection2 = NULL;lv_obj_t *ui_Label20 = NULL;lv_obj_t *ui_Button4 = NULL;lv_obj_t *ui_Label21 = NULL;lv_obj_t *ui_Button7 = NULL;lv_obj_t *ui_Label29 = NULL;lv_obj_t *ui_maxPumpSpdTmpSlider = NULL;lv_obj_t *ui_Label39 = NULL;lv_obj_t *ui_minPumpSpdTmpSlider = NULL;lv_obj_t *ui_Label53 = NULL;lv_obj_t *ui_maxFanSpdTmpSlider = NULL;lv_obj_t *ui_Label54 = NULL;lv_obj_t *ui_minFanSpdTmpSlider = NULL;lv_obj_t *ui_Label55 = NULL;lv_obj_t *ui_defaultBandDropdown = NULL;lv_obj_t *ui_maxPumpSpeedTmp = NULL;lv_obj_t *ui_maxFanSpeedTmp = NULL;lv_obj_t *ui_minPumpSpeedTmp = NULL;lv_obj_t *ui_minFanSpeedTmp = NULL;lv_obj_t *ui_protectionSwitch = NULL;lv_obj_t *ui_Label52 = NULL;
// event funtions
void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_protection, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_protection_screen_init);
}
}

void ui_event_Button7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_menu, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_menu_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      saveSettings( e );
}
}

void ui_event_maxPumpSpdTmpSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_maxPumpSpeedTmp, target, "", "");
}
}

void ui_event_minPumpSpdTmpSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_minPumpSpeedTmp, target, "", "");
}
}

void ui_event_maxFanSpdTmpSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_maxFanSpeedTmp, target, "", "");
}
}

void ui_event_minFanSpdTmpSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_minFanSpeedTmp, target, "", "");
}
}

// build funtions

void ui_protection2_screen_init(void)
{
ui_protection2 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_protection2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label20 = lv_label_create(ui_protection2);
lv_obj_set_width( ui_Label20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label20, -136 );
lv_obj_set_y( ui_Label20, -118 );
lv_obj_set_align( ui_Label20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label20,"Max pump speed temp");
lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button4 = lv_button_create(ui_protection2);
lv_obj_set_width( ui_Button4, 100);
lv_obj_set_height( ui_Button4, 50);
lv_obj_set_x( ui_Button4, -173 );
lv_obj_set_y( ui_Button4, 95 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label21 = lv_label_create(ui_protection2);
lv_obj_set_width( ui_Label21, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label21, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label21, -173 );
lv_obj_set_y( ui_Label21, 96 );
lv_obj_set_align( ui_Label21, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label21,"PREV");
lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button7 = lv_button_create(ui_protection2);
lv_obj_set_width( ui_Button7, 100);
lv_obj_set_height( ui_Button7, 50);
lv_obj_set_x( ui_Button7, 167 );
lv_obj_set_y( ui_Button7, 95 );
lv_obj_set_align( ui_Button7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label29 = lv_label_create(ui_protection2);
lv_obj_set_width( ui_Label29, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label29, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label29, 168 );
lv_obj_set_y( ui_Label29, 96 );
lv_obj_set_align( ui_Label29, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label29,"SAVE");
lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_maxPumpSpdTmpSlider = lv_slider_create(ui_protection2);
lv_slider_set_range(ui_maxPumpSpdTmpSlider, 10,100);
lv_slider_set_value( ui_maxPumpSpdTmpSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_maxPumpSpdTmpSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_maxPumpSpdTmpSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_maxPumpSpdTmpSlider, 150);
lv_obj_set_height( ui_maxPumpSpdTmpSlider, 10);
lv_obj_set_x( ui_maxPumpSpdTmpSlider, -146 );
lv_obj_set_y( ui_maxPumpSpdTmpSlider, -91 );
lv_obj_set_align( ui_maxPumpSpdTmpSlider, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_maxPumpSpdTmpSlider,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_maxPumpSpdTmpSlider, lv_obj_get_style_pad_right(ui_maxPumpSpdTmpSlider,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Label39 = lv_label_create(ui_protection2);
lv_obj_set_width( ui_Label39, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label39, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label39, 86 );
lv_obj_set_y( ui_Label39, -118 );
lv_obj_set_align( ui_Label39, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label39,"Min pump speed temp");
lv_obj_set_style_text_font(ui_Label39, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_minPumpSpdTmpSlider = lv_slider_create(ui_protection2);
lv_slider_set_range(ui_minPumpSpdTmpSlider, 10,100);
lv_slider_set_value( ui_minPumpSpdTmpSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_minPumpSpdTmpSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_minPumpSpdTmpSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_minPumpSpdTmpSlider, 150);
lv_obj_set_height( ui_minPumpSpdTmpSlider, 10);
lv_obj_set_x( ui_minPumpSpdTmpSlider, 74 );
lv_obj_set_y( ui_minPumpSpdTmpSlider, -90 );
lv_obj_set_align( ui_minPumpSpdTmpSlider, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_minPumpSpdTmpSlider,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_minPumpSpdTmpSlider, lv_obj_get_style_pad_right(ui_minPumpSpdTmpSlider,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Label53 = lv_label_create(ui_protection2);
lv_obj_set_width( ui_Label53, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label53, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label53, -147 );
lv_obj_set_y( ui_Label53, -64 );
lv_obj_set_align( ui_Label53, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label53,"Max fan speed temp");
lv_obj_set_style_text_font(ui_Label53, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_maxFanSpdTmpSlider = lv_slider_create(ui_protection2);
lv_slider_set_range(ui_maxFanSpdTmpSlider, 10,100);
lv_slider_set_value( ui_maxFanSpdTmpSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_maxFanSpdTmpSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_maxFanSpdTmpSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_maxFanSpdTmpSlider, 150);
lv_obj_set_height( ui_maxFanSpdTmpSlider, 10);
lv_obj_set_x( ui_maxFanSpdTmpSlider, -145 );
lv_obj_set_y( ui_maxFanSpdTmpSlider, -37 );
lv_obj_set_align( ui_maxFanSpdTmpSlider, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_maxFanSpdTmpSlider,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_maxFanSpdTmpSlider, lv_obj_get_style_pad_right(ui_maxFanSpdTmpSlider,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Label54 = lv_label_create(ui_protection2);
lv_obj_set_width( ui_Label54, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label54, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label54, 75 );
lv_obj_set_y( ui_Label54, -64 );
lv_obj_set_align( ui_Label54, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label54,"Min fan speed temp");
lv_obj_set_style_text_font(ui_Label54, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_minFanSpdTmpSlider = lv_slider_create(ui_protection2);
lv_slider_set_range(ui_minFanSpdTmpSlider, 10,100);
lv_slider_set_value( ui_minFanSpdTmpSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_minFanSpdTmpSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_minFanSpdTmpSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_minFanSpdTmpSlider, 150);
lv_obj_set_height( ui_minFanSpdTmpSlider, 10);
lv_obj_set_x( ui_minFanSpdTmpSlider, 74 );
lv_obj_set_y( ui_minFanSpdTmpSlider, -40 );
lv_obj_set_align( ui_minFanSpdTmpSlider, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_minFanSpdTmpSlider,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_minFanSpdTmpSlider, lv_obj_get_style_pad_right(ui_minFanSpdTmpSlider,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Label55 = lv_label_create(ui_protection2);
lv_obj_set_width( ui_Label55, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label55, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label55, -159 );
lv_obj_set_y( ui_Label55, -7 );
lv_obj_set_align( ui_Label55, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label55,"Default band");
lv_obj_set_style_text_font(ui_Label55, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_defaultBandDropdown = lv_dropdown_create(ui_protection2);
lv_dropdown_set_options( ui_defaultBandDropdown, "160m\n80m\n60m\n40m\n30m\n20m\n17m\n15m\n12m\n10m\n6m" );
lv_obj_set_width( ui_defaultBandDropdown, 150);
lv_obj_set_height( ui_defaultBandDropdown, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_defaultBandDropdown, -151 );
lv_obj_set_y( ui_defaultBandDropdown, 27 );
lv_obj_set_align( ui_defaultBandDropdown, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_defaultBandDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_maxPumpSpeedTmp = lv_label_create(ui_protection2);
lv_obj_set_width( ui_maxPumpSpeedTmp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_maxPumpSpeedTmp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_maxPumpSpeedTmp, -44 );
lv_obj_set_y( ui_maxPumpSpeedTmp, -92 );
lv_obj_set_align( ui_maxPumpSpeedTmp, LV_ALIGN_CENTER );
lv_label_set_text(ui_maxPumpSpeedTmp,"XX");
lv_obj_set_style_text_font(ui_maxPumpSpeedTmp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_maxFanSpeedTmp = lv_label_create(ui_protection2);
lv_obj_set_width( ui_maxFanSpeedTmp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_maxFanSpeedTmp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_maxFanSpeedTmp, -45 );
lv_obj_set_y( ui_maxFanSpeedTmp, -36 );
lv_obj_set_align( ui_maxFanSpeedTmp, LV_ALIGN_CENTER );
lv_label_set_text(ui_maxFanSpeedTmp,"XX");
lv_obj_set_style_text_font(ui_maxFanSpeedTmp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_minPumpSpeedTmp = lv_label_create(ui_protection2);
lv_obj_set_width( ui_minPumpSpeedTmp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_minPumpSpeedTmp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_minPumpSpeedTmp, 181 );
lv_obj_set_y( ui_minPumpSpeedTmp, -91 );
lv_obj_set_align( ui_minPumpSpeedTmp, LV_ALIGN_CENTER );
lv_label_set_text(ui_minPumpSpeedTmp,"XX");
lv_obj_set_style_text_font(ui_minPumpSpeedTmp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_minFanSpeedTmp = lv_label_create(ui_protection2);
lv_obj_set_width( ui_minFanSpeedTmp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_minFanSpeedTmp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_minFanSpeedTmp, 182 );
lv_obj_set_y( ui_minFanSpeedTmp, -43 );
lv_obj_set_align( ui_minFanSpeedTmp, LV_ALIGN_CENTER );
lv_label_set_text(ui_minFanSpeedTmp,"XX");
lv_obj_set_style_text_font(ui_minFanSpeedTmp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_protectionSwitch = lv_switch_create(ui_protection2);
lv_obj_set_width( ui_protectionSwitch, 92);
lv_obj_set_height( ui_protectionSwitch, 32);
lv_obj_set_x( ui_protectionSwitch, 85 );
lv_obj_set_y( ui_protectionSwitch, 27 );
lv_obj_set_align( ui_protectionSwitch, LV_ALIGN_CENTER );

ui_Label52 = lv_label_create(ui_protection2);
lv_obj_set_width( ui_Label52, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label52, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label52, 87 );
lv_obj_set_y( ui_Label52, -7 );
lv_obj_set_align( ui_Label52, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label52,"Enable protection");
lv_obj_set_style_text_font(ui_Label52, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_maxPumpSpdTmpSlider, ui_event_maxPumpSpdTmpSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_minPumpSpdTmpSlider, ui_event_minPumpSpdTmpSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_maxFanSpdTmpSlider, ui_event_maxFanSpdTmpSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_minFanSpdTmpSlider, ui_event_minFanSpdTmpSlider, LV_EVENT_ALL, NULL);

}

void ui_protection2_screen_destroy(void)
{
   if (ui_protection2) lv_obj_del(ui_protection2);

// NULL screen variables
ui_protection2= NULL;
ui_Label20= NULL;
ui_Button4= NULL;
ui_Label21= NULL;
ui_Button7= NULL;
ui_Label29= NULL;
ui_maxPumpSpdTmpSlider= NULL;
ui_Label39= NULL;
ui_minPumpSpdTmpSlider= NULL;
ui_Label53= NULL;
ui_maxFanSpdTmpSlider= NULL;
ui_Label54= NULL;
ui_minFanSpdTmpSlider= NULL;
ui_Label55= NULL;
ui_defaultBandDropdown= NULL;
ui_maxPumpSpeedTmp= NULL;
ui_maxFanSpeedTmp= NULL;
ui_minPumpSpeedTmp= NULL;
ui_minFanSpeedTmp= NULL;
ui_protectionSwitch= NULL;
ui_Label52= NULL;

}
