// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#ifndef UI_PROTECTION_H
#define UI_PROTECTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_protection
extern void ui_protection_screen_init(void);
extern void ui_protection_screen_destroy(void);
extern void ui_event_protection( lv_event_t * e);
extern lv_obj_t *ui_protection;
extern lv_obj_t *ui_Label18;
extern lv_obj_t *ui_Label19;
extern void ui_event_swrSlider( lv_event_t * e);
extern lv_obj_t *ui_swrSlider;
extern void ui_event_currentSlider( lv_event_t * e);
extern lv_obj_t *ui_currentSlider;
extern lv_obj_t *ui_maxSWR;
extern lv_obj_t *ui_maxCurr;
extern void ui_event_Button8( lv_event_t * e);
extern lv_obj_t *ui_Button8;
extern lv_obj_t *ui_Label22;
extern void ui_event_Button9( lv_event_t * e);
extern lv_obj_t *ui_Button9;
extern lv_obj_t *ui_Label23;
extern void ui_event_voltageSlider( lv_event_t * e);
extern lv_obj_t *ui_voltageSlider;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_waterTmpSliderLabel;
extern void ui_event_waterTmpSlider( lv_event_t * e);
extern lv_obj_t *ui_waterTmpSlider;
extern lv_obj_t *ui_Label15;
extern void ui_event_plateTmpSlider( lv_event_t * e);
extern lv_obj_t *ui_plateTmpSlider;
extern lv_obj_t *ui_maxVoltage;
extern lv_obj_t *ui_maxPlateTemp;
extern lv_obj_t *ui_maxWaterTemp;
extern void ui_event_maxIPWRSlider( lv_event_t * e);
extern lv_obj_t *ui_maxIPWRSlider;
extern lv_obj_t *ui_Label57;
extern lv_obj_t *ui_maxIPWR;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

