// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#include "ui.h"

lv_obj_t *ui_protection = NULL;lv_obj_t *ui_Label18 = NULL;lv_obj_t *ui_Label19 = NULL;lv_obj_t *ui_swrSlider = NULL;lv_obj_t *ui_currentSlider = NULL;lv_obj_t *ui_maxSWR = NULL;lv_obj_t *ui_maxCurr = NULL;lv_obj_t *ui_Button8 = NULL;lv_obj_t *ui_Label22 = NULL;lv_obj_t *ui_Button9 = NULL;lv_obj_t *ui_Label23 = NULL;lv_obj_t *ui_voltageSlider = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_waterTmpSliderLabel = NULL;lv_obj_t *ui_waterTmpSlider = NULL;lv_obj_t *ui_Label15 = NULL;lv_obj_t *ui_plateTmpSlider = NULL;lv_obj_t *ui_maxVoltage = NULL;lv_obj_t *ui_maxPlateTemp = NULL;lv_obj_t *ui_maxWaterTemp = NULL;lv_obj_t *ui_maxIPWRSlider = NULL;lv_obj_t *ui_Label57 = NULL;lv_obj_t *ui_maxIPWR = NULL;
// event funtions
void ui_event_protection( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      protectionOpened( e );
}
}

void ui_event_swrSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_label_set_property(ui_maxSWR, _UI_LABEL_PROPERTY_TEXT, "");
}
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_maxSWR, target, "", "");
}
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      _ui_slider_set_text_value( ui_maxSWR, target, "", "");
}
}

void ui_event_currentSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_maxCurr, target, "", "");
}
}

void ui_event_Button8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_protection2, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_protection2_screen_init);
      settingsNext( e );
}
}

void ui_event_Button9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_menu, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_menu_screen_init);
}
}

void ui_event_voltageSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_maxVoltage, target, "", "");
}
}

void ui_event_waterTmpSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_maxWaterTemp, target, "", "");
}
}

void ui_event_plateTmpSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_maxPlateTemp, target, "", "");
}
}

void ui_event_maxIPWRSlider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_maxIPWR, target, "", "");
}
}

// build funtions

void ui_protection_screen_init(void)
{
ui_protection = lv_obj_create(NULL);
lv_obj_remove_flag( ui_protection, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label18 = lv_label_create(ui_protection);
lv_obj_set_width( ui_Label18, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label18, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label18, -180 );
lv_obj_set_y( ui_Label18, -117 );
lv_obj_set_align( ui_Label18, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label18,"Max SWR");
lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label19 = lv_label_create(ui_protection);
lv_obj_set_width( ui_Label19, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label19, 73 );
lv_obj_set_y( ui_Label19, -117 );
lv_obj_set_align( ui_Label19, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label19,"Max current");
lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_swrSlider = lv_slider_create(ui_protection);
lv_slider_set_range(ui_swrSlider, 2,4);
lv_slider_set_value( ui_swrSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_swrSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_swrSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_swrSlider, 150);
lv_obj_set_height( ui_swrSlider, 10);
lv_obj_set_x( ui_swrSlider, -146 );
lv_obj_set_y( ui_swrSlider, -83 );
lv_obj_set_align( ui_swrSlider, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_swrSlider,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_swrSlider, lv_obj_get_style_pad_right(ui_swrSlider,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_currentSlider = lv_slider_create(ui_protection);
lv_slider_set_range(ui_currentSlider, 5,55);
lv_slider_set_value( ui_currentSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_currentSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_currentSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_currentSlider, 150);
lv_obj_set_height( ui_currentSlider, 10);
lv_obj_set_x( ui_currentSlider, 96 );
lv_obj_set_y( ui_currentSlider, -83 );
lv_obj_set_align( ui_currentSlider, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_currentSlider,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_currentSlider, lv_obj_get_style_pad_right(ui_currentSlider,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_maxSWR = lv_label_create(ui_protection);
lv_obj_set_width( ui_maxSWR, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_maxSWR, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_maxSWR, -55 );
lv_obj_set_y( ui_maxSWR, -82 );
lv_obj_set_align( ui_maxSWR, LV_ALIGN_CENTER );
lv_label_set_text(ui_maxSWR,"X");
lv_obj_set_style_text_font(ui_maxSWR, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_maxCurr = lv_label_create(ui_protection);
lv_obj_set_width( ui_maxCurr, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_maxCurr, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_maxCurr, 196 );
lv_obj_set_y( ui_maxCurr, -82 );
lv_obj_set_align( ui_maxCurr, LV_ALIGN_CENTER );
lv_label_set_text(ui_maxCurr,"XX");
lv_obj_set_style_text_font(ui_maxCurr, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button8 = lv_button_create(ui_protection);
lv_obj_set_width( ui_Button8, 129);
lv_obj_set_height( ui_Button8, 50);
lv_obj_set_x( ui_Button8, 154 );
lv_obj_set_y( ui_Button8, 95 );
lv_obj_set_align( ui_Button8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label22 = lv_label_create(ui_protection);
lv_obj_set_width( ui_Label22, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label22, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label22, 154 );
lv_obj_set_y( ui_Label22, 96 );
lv_obj_set_align( ui_Label22, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label22,"NEXT");
lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button9 = lv_button_create(ui_protection);
lv_obj_set_width( ui_Button9, 129);
lv_obj_set_height( ui_Button9, 50);
lv_obj_set_x( ui_Button9, -154 );
lv_obj_set_y( ui_Button9, 95 );
lv_obj_set_align( ui_Button9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label23 = lv_label_create(ui_protection);
lv_obj_set_width( ui_Label23, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label23, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label23, -155 );
lv_obj_set_y( ui_Label23, 96 );
lv_obj_set_align( ui_Label23, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label23,"DISCARD");
lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_voltageSlider = lv_slider_create(ui_protection);
lv_slider_set_range(ui_voltageSlider, 10,60);
lv_slider_set_value( ui_voltageSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_voltageSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_voltageSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_voltageSlider, 150);
lv_obj_set_height( ui_voltageSlider, 10);
lv_obj_set_x( ui_voltageSlider, -146 );
lv_obj_set_y( ui_voltageSlider, -20 );
lv_obj_set_align( ui_voltageSlider, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_voltageSlider,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_voltageSlider, lv_obj_get_style_pad_right(ui_voltageSlider,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Label9 = lv_label_create(ui_protection);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label9, -171 );
lv_obj_set_y( ui_Label9, -48 );
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Max voltage");
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_waterTmpSliderLabel = lv_label_create(ui_protection);
lv_obj_set_width( ui_waterTmpSliderLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_waterTmpSliderLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_waterTmpSliderLabel, 92 );
lv_obj_set_y( ui_waterTmpSliderLabel, 13 );
lv_obj_set_align( ui_waterTmpSliderLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_waterTmpSliderLabel,"Max water temp");
lv_obj_set_style_text_font(ui_waterTmpSliderLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_waterTmpSlider = lv_slider_create(ui_protection);
lv_slider_set_range(ui_waterTmpSlider, 10,100);
lv_slider_set_value( ui_waterTmpSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_waterTmpSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_waterTmpSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_waterTmpSlider, 150);
lv_obj_set_height( ui_waterTmpSlider, 10);
lv_obj_set_x( ui_waterTmpSlider, 96 );
lv_obj_set_y( ui_waterTmpSlider, 36 );
lv_obj_set_align( ui_waterTmpSlider, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_waterTmpSlider,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_waterTmpSlider, lv_obj_get_style_pad_right(ui_waterTmpSlider,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Label15 = lv_label_create(ui_protection);
lv_obj_set_width( ui_Label15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label15, -157 );
lv_obj_set_y( ui_Label15, 13 );
lv_obj_set_align( ui_Label15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label15,"Max plate temp");
lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_plateTmpSlider = lv_slider_create(ui_protection);
lv_slider_set_range(ui_plateTmpSlider, 10,100);
lv_slider_set_value( ui_plateTmpSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_plateTmpSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_plateTmpSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_plateTmpSlider, 150);
lv_obj_set_height( ui_plateTmpSlider, 10);
lv_obj_set_x( ui_plateTmpSlider, -146 );
lv_obj_set_y( ui_plateTmpSlider, 39 );
lv_obj_set_align( ui_plateTmpSlider, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_plateTmpSlider,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_plateTmpSlider, lv_obj_get_style_pad_right(ui_plateTmpSlider,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_maxVoltage = lv_label_create(ui_protection);
lv_obj_set_width( ui_maxVoltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_maxVoltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_maxVoltage, -50 );
lv_obj_set_y( ui_maxVoltage, -24 );
lv_obj_set_align( ui_maxVoltage, LV_ALIGN_CENTER );
lv_label_set_text(ui_maxVoltage,"XX");
lv_obj_set_style_text_font(ui_maxVoltage, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_maxPlateTemp = lv_label_create(ui_protection);
lv_obj_set_width( ui_maxPlateTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_maxPlateTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_maxPlateTemp, -48 );
lv_obj_set_y( ui_maxPlateTemp, 39 );
lv_obj_set_align( ui_maxPlateTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_maxPlateTemp,"XX");
lv_obj_set_style_text_font(ui_maxPlateTemp, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_maxWaterTemp = lv_label_create(ui_protection);
lv_obj_set_width( ui_maxWaterTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_maxWaterTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_maxWaterTemp, 195 );
lv_obj_set_y( ui_maxWaterTemp, 39 );
lv_obj_set_align( ui_maxWaterTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_maxWaterTemp,"XX");
lv_obj_set_style_text_font(ui_maxWaterTemp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_maxIPWRSlider = lv_slider_create(ui_protection);
lv_slider_set_range(ui_maxIPWRSlider, 1,10);
lv_slider_set_value( ui_maxIPWRSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_maxIPWRSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_maxIPWRSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_maxIPWRSlider, 150);
lv_obj_set_height( ui_maxIPWRSlider, 10);
lv_obj_set_x( ui_maxIPWRSlider, 96 );
lv_obj_set_y( ui_maxIPWRSlider, -20 );
lv_obj_set_align( ui_maxIPWRSlider, LV_ALIGN_CENTER );

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_maxIPWRSlider,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_maxIPWRSlider, lv_obj_get_style_pad_right(ui_maxIPWRSlider,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_Label57 = lv_label_create(ui_protection);
lv_obj_set_width( ui_Label57, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label57, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label57, 93 );
lv_obj_set_y( ui_Label57, -48 );
lv_obj_set_align( ui_Label57, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label57,"Max input power");
lv_obj_set_style_text_font(ui_Label57, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_maxIPWR = lv_label_create(ui_protection);
lv_obj_set_width( ui_maxIPWR, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_maxIPWR, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_maxIPWR, 197 );
lv_obj_set_y( ui_maxIPWR, -22 );
lv_obj_set_align( ui_maxIPWR, LV_ALIGN_CENTER );
lv_label_set_text(ui_maxIPWR,"XX");
lv_obj_set_style_text_font(ui_maxIPWR, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_swrSlider, ui_event_swrSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_currentSlider, ui_event_currentSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button9, ui_event_Button9, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_voltageSlider, ui_event_voltageSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_waterTmpSlider, ui_event_waterTmpSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_plateTmpSlider, ui_event_plateTmpSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_maxIPWRSlider, ui_event_maxIPWRSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_protection, ui_event_protection, LV_EVENT_ALL, NULL);

}

void ui_protection_screen_destroy(void)
{
   if (ui_protection) lv_obj_del(ui_protection);

// NULL screen variables
ui_protection= NULL;
ui_Label18= NULL;
ui_Label19= NULL;
ui_swrSlider= NULL;
ui_currentSlider= NULL;
ui_maxSWR= NULL;
ui_maxCurr= NULL;
ui_Button8= NULL;
ui_Label22= NULL;
ui_Button9= NULL;
ui_Label23= NULL;
ui_voltageSlider= NULL;
ui_Label9= NULL;
ui_waterTmpSliderLabel= NULL;
ui_waterTmpSlider= NULL;
ui_Label15= NULL;
ui_plateTmpSlider= NULL;
ui_maxVoltage= NULL;
ui_maxPlateTemp= NULL;
ui_maxWaterTemp= NULL;
ui_maxIPWRSlider= NULL;
ui_Label57= NULL;
ui_maxIPWR= NULL;

}
