// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#ifndef UI_WARNING_H
#define UI_WARNING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_warning
extern void ui_warning_screen_init(void);
extern void ui_warning_screen_destroy(void);
extern lv_obj_t *ui_warning;
extern lv_obj_t *ui_alertReason;
extern void ui_event_Button11( lv_event_t * e);
extern lv_obj_t *ui_Button11;
extern lv_obj_t *ui_Label56;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

