// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#ifndef UI_WIFI_H
#define UI_WIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_wifi
extern void ui_wifi_screen_init(void);
extern void ui_wifi_screen_destroy(void);
extern lv_obj_t *ui_wifi;
extern lv_obj_t *ui_Keyboard1;
extern lv_obj_t *ui_Label25;
extern void ui_event_TextArea1( lv_event_t * e);
extern lv_obj_t *ui_TextArea1;
extern lv_obj_t *ui_Label26;
extern void ui_event_TextArea3( lv_event_t * e);
extern lv_obj_t *ui_TextArea3;
extern void ui_event_Button10( lv_event_t * e);
extern lv_obj_t *ui_Button10;
extern lv_obj_t *ui_Label27;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

