// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: pa_ctl

#include "ui.h"

lv_obj_t *ui_warning = NULL;lv_obj_t *ui_alertReason = NULL;lv_obj_t *ui_Button11 = NULL;lv_obj_t *ui_Label56 = NULL;
// event funtions
void ui_event_Button11( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      resetAlert( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_main, LV_SCR_LOAD_ANIM_OUT_BOTTOM, 500, 0, &ui_main_screen_init);
}
}

// build funtions

void ui_warning_screen_init(void)
{
ui_warning = lv_obj_create(NULL);
lv_obj_remove_flag( ui_warning, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_alertReason = lv_label_create(ui_warning);
lv_obj_set_width( ui_alertReason, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_alertReason, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_alertReason, LV_ALIGN_CENTER );
lv_label_set_text(ui_alertReason,"ALERT TRIGGERED");
lv_obj_set_style_text_font(ui_alertReason, &lv_font_montserrat_28, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button11 = lv_button_create(ui_warning);
lv_obj_set_width( ui_Button11, 100);
lv_obj_set_height( ui_Button11, 50);
lv_obj_set_x( ui_Button11, -2 );
lv_obj_set_y( ui_Button11, 94 );
lv_obj_set_align( ui_Button11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button11, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label56 = lv_label_create(ui_warning);
lv_obj_set_width( ui_Label56, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label56, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label56, -4 );
lv_obj_set_y( ui_Label56, 95 );
lv_obj_set_align( ui_Label56, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label56,"RESET");

lv_obj_add_event_cb(ui_Button11, ui_event_Button11, LV_EVENT_ALL, NULL);

}

void ui_warning_screen_destroy(void)
{
   if (ui_warning) lv_obj_del(ui_warning);

// NULL screen variables
ui_warning= NULL;
ui_alertReason= NULL;
ui_Button11= NULL;
ui_Label56= NULL;

}
